# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Activeledger-SDK-IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Activeledger-SDK-IOS

	pod 'Alamofire', '~> 5.0.0-rc.3'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'SwiftyRSA'

end
